### ISSUE TITLE
Error in read_input(file) : file must be connection, raw vector or file path

### ISSUE THREAD

**Issue by jrangeles** [r-lib/httr#340]
I'm trying to use the oauth_service_token() for google analytics, but I'm getting this error:

```
Error in read_input(file) : 
  file must be connection, raw vector or file path
```

I'm not sure what the problem is since I can call the json file through jsonlite's fromJSON function.

This error actually came about after experiencing this error:

```
 Error: Refresh token not available 
6 stop("Refresh token not available", call. = FALSE) 
5 refresh_oauth2.0(self$endpoint, self$app, self$credentials, self$params$user_params) 
4 token$refresh() 
3 validate_token(token) 
2 authorize(client.id = options()$rga$client_id, client.secret = options()$rga$client_secret, 
    reauth = FALSE, cache = "token") 
```

I'm really after fixing the "Error: Refresh token not available".

**Comment by ericbrownaustin** [comment]
I am having the same issue.

**Comment by aam044** [comment]
Having the same when try to use service account json

**Comment by samfield** [comment]
I find myself in somewhat similar situation; I'm able to use oauth_service_token with an Ubuntu provisioned in cloud but fail with running the same code in local Win7 setup.

I'm running older package versions on Ubuntu (due to previous issues between httr and bigquery)


**Reproducible examples:**

**Ubuntu:**
`install.packages("devtools")
install_github("hadley/httr@7261a52")
#---snip-----
#---snap----

#prepare token
endpoint_gce <- oauth_endpoints("google")
secrets_gce <- jsonlite::fromJSON("path/to/my.json")
scope_gce_bigqr <- c("https://www.googleapis.com/auth/bigquery")
#set token
token <- oauth_service_token(
  endpoint = endpoint_gce,
  secrets = secrets_gce,
  scope = scope_gce_bigqr)
#Result ok`

**packages on Ubuntu:**

`> session_info()
Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2016-04-28                  

Packages ---------------------------------------------------------------------------------------------------
 package  * version    date       source                      
 curl       0.9.7      2016-04-10 CRAN (R 3.2.3)              
 devtools * 1.11.1     2016-04-21 CRAN (R 3.2.3)              
 digest     0.6.9      2016-01-08 CRAN (R 3.1.1)              
 git2r      0.13.1     2015-12-10 CRAN (R 3.2.3)              
 httr     * 1.1.0.9000 2016-04-28 Github (hadley/httr@7261a52)
 jsonlite   0.9.19     2015-11-28 CRAN (R 3.2.3)              
 knitr      1.12.3     2016-01-22 CRAN (R 3.2.3)              
 memoise    1.0.0      2016-01-29 CRAN (R 3.2.3)              
 openssl    0.9.2      2016-02-26 CRAN (R 3.2.3)              
 R6         2.1.2      2016-01-26 CRAN (R 3.2.3)              
 withr      1.0.1      2016-02-04 CRAN (R 3.2.3)`


**Win7 Local**
`install.packages("devtools")
library(devtools)
install_github("hadley/httr@7261a52")
library(httr)

endpoint_gce <- oauth_endpoints("google")
secrets_gce <- jsonlite::fromJSON("path/to/my.json")
scope_gce_bigqr <- c("https://www.googleapis.com/auth/bigquery")
#set token
token <- oauth_service_token(endpoint = endpoint_gce,
                             secrets = secrets_gce,
                             scope = scope_gce_bigqr)`
**Resulting in:
Error in read_input(file) : 
  file must be connection, raw vector or file path**

**packages in Windows**

`> session_info()
Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.467)          
 language (EN)                        
 collate  Finnish_Finland.1252        
 tz       Europe/Helsinki             
 date     2016-04-28                  

Packages ----------------------------------------------------------------------------------------
 package  * version    date       source                      
 curl       0.9.7      2016-04-10 CRAN (R 3.2.5)              
 devtools * 1.11.1     2016-04-21 CRAN (R 3.2.5)              
 digest     0.6.9      2016-01-08 CRAN (R 3.2.5)              
 git2r      0.14.0     2016-03-13 CRAN (R 3.2.4)              
 httr     * 1.1.0.9000 2016-04-28 Github (hadley/httr@7261a52)
 jsonlite   0.9.19     2015-11-28 CRAN (R 3.2.5)              
 memoise    1.0.0      2016-01-29 CRAN (R 3.2.5)              
 openssl    0.9.2      2016-02-26 CRAN (R 3.2.5)              
 R6         2.1.2      2016-01-26 CRAN (R 3.2.5)              
 withr      1.0.1      2016-02-04 CRAN (R 3.2.5) `

The R version is a difference obviously. Unfortunately I'm unable to update that machine at this time.

Is there a view if this is expected behavior on httr and R 3.2.2 or might I be facing an issue with httr otherwise?

**Comment by samfield** [comment]
Now also verified the same issue with updated R and RStudio

```
Session info -----------------------------------------------------
 setting  value                       
 version  R version 3.2.5 (2016-04-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.896)          
 language (EN)                        
 collate  Finnish_Finland.1252        
 tz       Europe/Helsinki             
 date     2016-05-03       
```

**Comment by hadley** [comment]
@samfield could you please give me a `traceback()`? I don't think the problem is coming from httr, given that I don't see `read_input` anywhere in httr.

**Comment by hadley** [comment]
FWIW if I don't get a traceback in the next couple of days, this will have to wait until the next release

**Comment by MarkEdmondson1234** [comment]
I think this may be due to a change in how `jsonlite` reads in the JSON, perhaps Google's file or the parser has changed, but there now seems to be a "installed" root which isn't expected by `init_oauth_service_account`:

```r
> jsonlite::fromJSON("~/dev/auth/client_secret_XXX.apps.googleusercontent.com.json")
$installed
$installed$client_id
[1] "XXXX.apps.googleusercontent.com"

$installed$project_id
[1] "mark-edmondson-gde"

$installed$auth_uri
[1] "https://accounts.google.com/o/oauth2/auth"

$installed$token_uri
[1] "https://accounts.google.com/o/oauth2/token"

$installed$auth_provider_x509_cert_url
[1] "https://www.googleapis.com/oauth2/v1/certs"
```
JSON:

```
{
    "installed": {
        "client_id": "XXX.apps.googleusercontent.com",
        "project_id": "mark-xx-gde",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
    }
}
```

**Comment by MarkEdmondson1234** [comment]
A few `browsers` later its narrowed down to `jwt_signature` expecting `credentials$private_key` but this doesn't exist in the JSON.

```
jwt_signature <- function(credentials, scope, aud, duration = 60L * 60L) {
  browser()
  now <- as.integer(Sys.time())
  cs <- jwt_claimset(credentials$client_email, scope, aud = aud, iat = now,
    exp = now + duration)
  jwt_sign(cs, credentials$private_key)
}
```

**Comment by MarkEdmondson1234** [comment]
Ok, its just the wrong JSON file being used 👍 O_o

Use "Service account keys" at the bottom, not service account client from OAuth2 Client Ids.

**Comment by GauravJoshi13** [comment]
@MarkEdmondson1234  - can you please share the required json file template.

**Comment by hadley** [comment]
@GauravJoshi13 asking questions on 4 year old issues isn't a good approach. Please ask elsewhere.
