### ISSUE TITLE
Peer's Certificate issuer is not recognized.

### ISSUE THREAD

**Issue by Nosferican** [r-lib/httr#531]
Issue with Peer's Certificate issuer.

```
licences = 'http://www.abc.virginia.gov/library/enforcement/other-documents/finalboardorders_july2015-june2016.xls?la=en' %>%
  GET()
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer's Certificate issuer is not recognized.
```
Base site is: [ABC Final Decisions Files](https://www.abc.virginia.gov/enforcement/hearings-and-appeals/final-decisions)

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by Nosferican** [comment]
It seems since then the website has updated their certificate since then. Since the issue is with the certificate we cannot use a web.archive version of the website for testing purposes. To reproduce the issue one would have to find a website with a faulty/weird Peer's Certificate issuer. I think we can close this issue until someone attempts to request a webpage with faulty/weird Peer's Certificate issuer and identify the exact issue before the website fixes it.
