### ISSUE TITLE
Provide option not to remove empty body fields in PUT/POST/PATCH

### ISSUE THREAD

**Issue by Hong-Revo** [r-lib/httr#573]
Something I just realized: `PUT`, `POST` and `PATCH` will silently remove empty fields in an encoded request body, due to the [following line](https://github.com/r-lib/httr/blob/master/R/body.R#L50) in `body_config`:

```r
  if (!is.list(body)) {
    stop("Unknown type of `body`: must be NULL, FALSE, character, raw or list",
      call. = FALSE
    )
  }

  body <- compact(body)   # <---- right here

  # Deal with three ways to encode: form, multipart & json
  encode <- match.arg(encode)
```

Most of the time this is harmless, but sometimes the presence or absence of a field can be meaningful, eg an empty field means "delete this component" whereas leaving it out means "leave this component unchanged".

Can these verbs have an option to keep empty fields in the request body? Or if development work is switching to httr2, provide this option in the new package.

**Comment by cderv** [comment]
You can pass empty parts in body with `httr` if you use `raw` or `character` body. 
There is a question on this in #561. Here some example code I have made there: 

``` r
httr::POST("https://httpbin.org/post", body = '{"a":1,"b":{}}', encode = "raw")
#> Response [https://httpbin.org/post]
#>   Date: 2019-01-03 20:53
#>   Status: 200
#>   Content-Type: application/json
#>   Size: 464 B
#> {
#>   "args": {}, 
#>   "data": "{\"a\":1,\"b\":{}}", 
#>   "files": {}, 
#>   "form": {}, 
#>   "headers": {
#>     "Accept": "application/json, text/xml, application/xml, */*", 
#>     "Accept-Encoding": "gzip, deflate", 
#>     "Connection": "close", 
#>     "Content-Length": "14", 
#> ...
```

or build the body directly using `jsonlite`

``` r
json_body <- jsonlite::toJSON(list(a = 1, b = NULL), auto_unbox = TRUE)
httr::POST("https://httpbin.org/post", body = json_body, encode = "raw")
#> Response [https://httpbin.org/post]
#>   Date: 2019-01-03 20:53
#>   Status: 200
#>   Content-Type: application/json
#>   Size: 464 B
#> {
#>   "args": {}, 
#>   "data": "{\"a\":1,\"b\":{}}", 
#>   "files": {}, 
#>   "form": {}, 
#>   "headers": {
#>     "Accept": "application/json, text/xml, application/xml, */*", 
#>     "Accept-Encoding": "gzip, deflate", 
#>     "Connection": "close", 
#>     "Content-Length": "14", 
#> ...
```

<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup> 

The `encode = "raw"` is not needed really because character body will stay as is, but it helps remember. 
Using `jsonlite` externaly to httr to build the body is the main way to customise the body.

Could this fill your needs for empty body fields ?

**Comment by Hong-Revo** [comment]
Ta, didn't realise this is a dup.
