### ISSUE TITLE
RETRY errors on curl timeout

### ISSUE THREAD

**Issue by adam-cornwell** [r-lib/httr#574]
I recently started trying to use httr for RETRY because I've been getting intermittent errors in the middle of a long set of remote API calls. However, it seems like when CURL times out- and doesn't provide an HTTP status code- RETRY dies. I would expect that RETRY would retry even in these cases. Since the documentation doesn't mention this kind of timeout, I'm not sure if this is a bug report or a feature request.

Simple reproducible example-
This dies:
`RETRY("GET", "http://httpbin.org/delay/3", timeout(1))`
`#Error in UseMethod("http_error") : 
  no applicable method for 'http_error' applied to an object of class "c('simpleError', 'error', 'condition')"`

This is fine:
`RETRY("GET", "http://httpbin.org/delay/3", timeout(4))`

R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200
httr_1.4.0.9000

**Comment by cderv** [comment]
This happens here 
https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/retry.R#L79-L91

`resp` is the response from curl. The timeout set create an error with curl. 
```sh
<simpleError in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: Operation timed out after 1000 milliseconds with 0 bytes received>
```
It could be a bug as there is a test for `resp` as an error line 84, but it happens after  `http_error(resp)` on line 80, causing the error you see. I think the error test should be before. 

Currently, it will retry on error only if you try with `terminate_on_success = FALSE` (this will skip the first test in if statement), you'll see the error of the curl request
``` r
library(httr)
RETRY("GET", "http://httpbin.org/delay/3", timeout(1), terminate_on_success = FALSE)
#> Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: Operation timed out after 1000 milliseconds with 0 bytes received
#> Request failed [ERROR]. Retrying in 1 seconds...
#> Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: Operation timed out after 1000 milliseconds with 0 bytes received
#> Request failed [ERROR]. Retrying in 1.8 seconds...
#> Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: Operation timed out after 1000 milliseconds with 0 bytes received
```

<sup>Created on 2019-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

However, as you see in the error message, the timeout is set to something less that the page delay, so no matter the retry time, you won't get anything else in this example. 

Can you try on your api calls the RETRY with the argument `terminate_on_success = FALSE` so that it retry on curl error ? We'll see if this change something.

**Comment by adam-cornwell** [comment]
I will try that, thanks.
What is the intended use case of `terminate_on_success = FALSE`? It wasn't entirely clear to me from the documentation.

**Comment by cderv** [comment]
> What is the intended use case of `terminate_on_success = FALSE`? It wasn't entirely clear to me from the documentation.

By default, `RETRY` will terminate only on success and retry on errors. But you can provide some http codes in `terminate_on` to terminate (so not retry) on some specific codes. `terminate_on_success` will skip that and will terminate on success even if `terminate_on` is provided. 

In the case of this issue `terminate_on_success = FALSE` is for skipping the test is causing the error you see.

**Comment by cderv** [comment]
@adam-cornwell did it work for you ? I was hoping you would test it then if it worked we could see what adjustment need to be done. 
I think the retry on curl error should be by default, and personally I would leave the issue Opened

**Comment by adam-cornwell** [comment]
It did finish with `terminate_on_success = FALSE`, and I'm running it again with `terminate_on_success = TRUE` to make sure I actually get the error again, and that it's not just the remote server having a better day.

**Comment by adam-cornwell** [comment]
My set of calls did finish with `terminate_on_success = FALSE`, however I ran it again with `terminate_on_success = TRUE` to make sure I actually got the error again, and it seems like the remote server is having a better day, as it finished successfully that way as well. A few days ago the error would happen randomly, but consistently in the sense that I couldn't get through the batch. Either way, it might be nice to change that behavior on errors like curl timeouts, even though it may a bit of an edge case.
