### ISSUE TITLE
Add auto_unbox to httr::POST

### ISSUE THREAD

**Issue by autoblocs** [r-lib/httr#577]
Hi
Is possible to expose auto_unbox for json encode?

**Comment by cderv** [comment]
You can build your json string using `jsonlite` and pass it in the body  as character and precise `encode = "raw"` in`httr::POST`

See other related issue with example https://github.com/r-lib/httr/issues/573#issuecomment-464605719 and https://github.com/r-lib/httr/issues/561#issuecomment-451278328

This way you can use any argument of `jsonlite::toJSON` for your POST call.

**Comment by autoblocs** [comment]
Absolutely, and I tried your suggestion yesterday.
However when the api accepts only POST with json object your solution does not work.
Felipe

**Comment by ValeriVoev** [comment]
@cderv - don't know if this is because of poorly designed APIs but just passing the json string (resulting from `jsonlite::toJSON`) together with `encode = "raw"` doesn't always work. The https://api.statbank.dk/v1/subjects endpoint for some (I think not meaningful) reason requires singletons like `"recursive":[false]` in the body to be "boxed". After a lot of trial and error I made it finally work like this (values just examples), I had to explicitly `httr::add_headers("Content-Type" = "application/json")`:

```r
SUBJECTS_ENDPOINT <- "https://api.statbank.dk/v1/subjects"
call_body <- list(lang = "en",recursive = FALSE, includeTables = FALSE, subjects = c("02", "2419"))

json_body <- jsonlite::toJSON(call_body, auto_unbox = FALSE)

result <- httr::POST(SUBJECTS_ENDPOINT, httr::add_headers("Content-Type" = "application/json"), body = json_body, encode = "raw")
```
I think I could have spared a lot of headache if `auto_unbox` was exposed in `hotter::POST` ... not all APIs are well designed and sometimes a bit more flexibility for the developer is needed.
