### ISSUE TITLE
Header passing fails with header that starts with HTTP_

### ISSUE THREAD

**Issue by ben519** [r-lib/httr#590]
I'm using httr to query some data from the [Shopify API](https://help.shopify.com/en/api/reference). Every call I make generates the warning message "In parse_http_status(lines[[1]]) : NAs introduced by coercion". For example,

```
response <- GET(
  url = "https://test-store.myshopify.com/admin/orders/count.json",
  httr::add_headers(Accept = "application/json"),
  httr::authenticate(user = "abc", password = "def")
)

Warning message:
In parse_http_status(lines[[1]]) : NAs introduced by coercion
```

It seems that the culprit is this function

```
parse_http_headers <- function(raw) {
  lines <- strsplit(rawToChar(raw), "\r?\n")[[1]]

  new_response <- grepl("^HTTP", lines)
  grps <- cumsum(new_response)

  lapply(unname(split(lines, grps)), parse_single_header)
}
```
specifically this bit: `new_response <- grepl("^HTTP", lines)` that attempts to pick out HTTP status lines from the vector of `lines`. Shopify's API always returns a header line like "HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT: 1/40" and this is falsely getting identified as an HTTP status line. Further down, it's getting parsed and an `as.integer(status$status)` bit it causing the coercion warning.

Can the regex used to identify HTTP status lines be tightened to prevent this false positive? Apologies - I don't know enough about possible HTTP status formats to make a good suggestion.

Thanks!

**Comment by sharlagelfand** [comment]
I'm interested in getting this fixed for an API I'm working with (the offending header in my case is `HTTP_API_VERSION: v0.19.2`) and happy to make a PR, but I also don't know enough about HTTP status formats! 

Do status codes always start with `HTTP/`? Seems like all the ones being tested do (https://github.com/r-lib/httr/blob/master/tests/testthat/test-header.r#L24) so I'm happy to update the offending line to check for that if that's the case - or maybe what's needed is that the line starts with `HTTP` but not `HTTP_`, as the updated title indicates?

ty!

**Comment by deschen1** [comment]
Not sure if of any help. But today I got the exact same warning for another API (Caplena - non-public, so can't share any reprex) that is new, i.e. it never occured before and I didn't change any code.

The specifc API request is (where `caplena_key` is my API key):

```
library(httr)
response <- GET(url = paste0("https://api.caplena.com/api/projects/"),
                add_headers("Authorization" = paste0("apikey ", caplena_key)))

Warning message:
In parse_http_status(lines[[1]]) : NAs introduced by coercion
```

The problem is, if I now want to turn the response object into something readable, I was able to do so previously with:

`projects <- content(response, encoding = "UTF-8")`

This returned a list obbject I could then process further.

Now, I have to change this to

`projects <- content(response, encoding = "UTF-8", type = "application/json")`

Any helpful information I should add here from the response objects (e.g. the headers or sth.)?

I checked with the developers of that API and they confirmed they didn't change anything. I also reverted the httr package to a status from late 2021 when the whole things definitely worked, but I still get the warning, so I'm a bit lost where this might come from.

**Comment by deschen1** [comment]
One small update. I tested it a bit further and the warning only occurs on Windows machines, NOT on MACs.

My IT suggests that it might indeed be related to this part here:

```
parse_http_headers <- function(raw) {
  lines <- strsplit(rawToChar(raw), "\r?\n")[[1]]

  new_response <- grepl("^HTTP", lines)
  grps <- cumsum(new_response)

  lapply(unname(split(lines, grps)), parse_single_header)
}
```

especially the second line, because there is no carriage return on Windows. Or the order of line break and carraige return is different than on Mac, (I didn't fully understand this part).

**Comment by deschen1** [comment]
Investigated a bit further here and first thing is that HTTP headers are case insensitive, so not sure what httr would return if a website uses lowercase (because the grepl in `parse_http_status` seems to check for uppercase HTTP): https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

And second thing is that the parsing of the status purely by the header starting with "http" is problematic. Maybe the header should be split and then checked if any element contains a number that would be a valid status response (e.g. a 200 or 404 or sth.).

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
