### ISSUE TITLE
Are the cookies not passed in the request header?

### ISSUE THREAD

**Issue by TyGu1** [r-lib/httr#629]
Example from the documentation:

`r <- GET("http://httpbin.org/cookies", set_cookies(a = 1, b = 2))`

I would expect the cookies being in the request header, because of this: https://stackoverflow.com/questions/3467114/how-are-cookies-passed-in-the-http-protocol:

```
r$request$headers
                                            Accept 
"application/json, text/xml, application/xml, */*"
```

 And i assume these are my request headers `req$request$headers`.

First asked here: https://stackoverflow.com/questions/59003863/are-the-cookies-not-passed-in-the-header-of-my-request-with-r.

**Comment by cderv** [comment]
To check if cookies are correctly sent and in the header, you can use httpbin to inspect cookies and headers from the request: 

``` r
library(httr)
# cookies are correctly sent during the request as tested with httpbin
r <- GET("https://httpbin.org/cookies", set_cookies(a = 1, b = 2))
content(r)
#> $cookies
#> $cookies$a
#> [1] "1"
#> 
#> $cookies$b
#> [1] "2"
# If you inspect the header of the sent request, Cookies are indeed in the header
r <- GET("https://httpbin.org/headers", set_cookies(a = 1, b = 2))
content(r)
#> $headers
#> $headers$Accept
#> [1] "application/json, text/xml, application/xml, */*"
#> 
#> $headers$`Accept-Encoding`
#> [1] "deflate, gzip"
#> 
#> $headers$Cookie
#> [1] "a=1;b=2"
#> 
#> $headers$Host
#> [1] "httpbin.org"
#> 
#> $headers$`User-Agent`
#> [1] "libcurl/7.64.1 r-curl/4.2 httr/1.4.1"
```

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

the `r$request` your are inspecting is an object created by httr to build the request. This is not the exact header that will be sent. This is I guess because httr is using curl 📦  in the backend and it is curl that handles cookies directly using `libcurl` support.
`httr::set_cookies` will pass the cookie to httr option `cookie` that correspond to curl option [`CURLOPT_COOKIE`](https://curl.haxx.se/libcurl/c/CURLOPT_COOKIE.html). It will be libcurl itself which will had the cookie header I guess.

Everything is working fine here I think. 

If you want to dig further, you can find information on how cookie are used with libcurl in https://ec.haxx.se/libcurl-http-cookies.html and this other doc from curl is interesting too
https://curl.haxx.se/docs/http-cookies.html

Hope it helps

**Comment by TyGu1** [comment]
Thanks so much for your answer. I know it is not my original Question and i am happy to close this issue if ist too much off-topic to ask:

Is there a way i can see which headers i sent (for other pages, e.g. r-Bloggers.com)?

**Comment by jennybc** [comment]
Putting httr commands inside `httr::with_verbose()` is generally very enlightening, when you're trying to see what exactly you are sending out.
