### ISSUE TITLE
oauth2.0_token with client_credentials = TRUE ignores scope parameter

### ISSUE THREAD

**Issue by pragmasoft-ua** [r-lib/httr#660]
When I use  oauth2.0_token with client_credentials = TRUE, httr does not post scope to the token endpoint

```r
token <- oauth2.0_token(okta, app,
  scope = "admin client",
  client_credentials = TRUE
)
```

I was able to fix the problem with user_params 

```r
token <- oauth2.0_token(okta, app,
  user_params = list(scope = "admin client"),
  client_credentials = TRUE
)
```

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄 — but OAuth support is much more robust in httr2 so it's quite likely this is already fixed there. Thanks for using httr!
