### ISSUE TITLE
How to setup OAuth 2.0 implicit grant flow ?

### ISSUE THREAD

**Issue by mariafb** [r-lib/httr#673]
How do we get the access_token from redirect URL implicit grant flow?

Example:

Request URL:
https://example.app/connect/authorize?client_id=implicit&scope=xxxx&redirect_uri=http:app/callback&response_type=token&state=xxxxxxx&nonce=xxxxxxx

Response:
https://example_redirect_uri/#access_token=xxxxxx&token_type=Beare&rexpires_in=1111&scope=xxxxxi&state=wwww

How can I implement implicit grant flow (response_type=token) and get the #access_token info with httr package in a shiny App. 

Anyone?

Thank you !

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄 — but httr2 generally offers much better OAuth support, so it's possible that it already just works. Thanks for using httr!
